name: 🚀 Deploy website on push

on:
  push:
    branches: master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.17.1]

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16.17.1
        uses: actions/setup-node@v2
        with:
          node-version: "16.17.1"

      - name: 🔨 Build Project
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true
          server-dir: public_html/brandingpioneers.com/
          local-dir: ./build/